USE [master]
GO
/****** Object:  Database [LibraryApp]    Script Date: 18/05/2024 23:26:38 ******/
CREATE DATABASE [LibraryApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
ALTER DATABASE [LibraryApp] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LibraryApp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LibraryApp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LibraryApp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LibraryApp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LibraryApp] SET ARITHABORT OFF 
GO
ALTER DATABASE [LibraryApp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LibraryApp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LibraryApp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LibraryApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LibraryApp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LibraryApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LibraryApp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LibraryApp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LibraryApp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LibraryApp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LibraryApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LibraryApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LibraryApp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LibraryApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LibraryApp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LibraryApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LibraryApp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LibraryApp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LibraryApp] SET  MULTI_USER 
GO
ALTER DATABASE [LibraryApp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LibraryApp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LibraryApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LibraryApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LibraryApp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LibraryApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LibraryApp] SET QUERY_STORE = OFF
GO
USE [LibraryApp]
GO
/****** Object:  Table [dbo].[Buku]    Script Date: 18/05/2024 23:26:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Buku](
	[IdBuku] [int] IDENTITY(1,1) NOT NULL,
	[NamaBuku] [nvarchar](500) NULL,
	[Rak] [nvarchar](500) NULL,
	[Stok] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mahasiswa]    Script Date: 18/05/2024 23:26:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mahasiswa](
	[IdMahasiswa] [int] IDENTITY(1,1) NOT NULL,
	[NIM] [nvarchar](500) NULL,
	[NamaMahasiswa] [nvarchar](500) NULL,
	[IsActive] [nvarchar](500) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Buku] ON 
GO
INSERT [dbo].[Buku] ([IdBuku], [NamaBuku], [Rak], [Stok]) VALUES (1, N'Buku 1', N'Rak A', 12)
GO
INSERT [dbo].[Buku] ([IdBuku], [NamaBuku], [Rak], [Stok]) VALUES (3, N'Buku 2', N'Rak B', 10)
GO
SET IDENTITY_INSERT [dbo].[Buku] OFF
GO
SET IDENTITY_INSERT [dbo].[Mahasiswa] ON 
GO
INSERT [dbo].[Mahasiswa] ([IdMahasiswa], [NIM], [NamaMahasiswa], [IsActive]) VALUES (1, N'1', N'Mahasiswa 1', N'0')
GO
INSERT [dbo].[Mahasiswa] ([IdMahasiswa], [NIM], [NamaMahasiswa], [IsActive]) VALUES (3, N'2', N'Mahasiswa 2', N'1')
GO
SET IDENTITY_INSERT [dbo].[Mahasiswa] OFF
GO
USE [master]
GO
ALTER DATABASE [LibraryApp] SET  READ_WRITE 
GO
